# =============================================================================================
# = Global Spring configuration
# =============================================================================================
# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping2?createDatabaseIfNotExist=true
    username: root
    password:

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    database-platform: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = JavaMail Configuration
# ===============================
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: FreeSafeSoft@gmail.com
    password:
    properties.mail:
      transport.protocol: smtps
      smtps.auth: true
      smtps.starttls.enable: true
      smtps.timeout: 8000
# =============================================================================================
# = Global Spring configuration
# =============================================================================================

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.fss.shopping: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO